---
repos:
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.30
    hooks:
      - id: conform
        stages:
          - commit-msg
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      - id: gofumpt
      - id: golangci-lint
        args: [
            "-c .golangci.yml"
        ]
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: go-mod-tidy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [
            "--allow-missing-credentials"
        ]
      - id: detect-private-key
#      - id: no-commit-to-branch
#        args: [
#            "--branch",
#            "master",
#            "--branch",
#            "next"
#        ]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
